///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Licenta_Nohai
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Change_name_and_surname recording.
    /// </summary>
    [TestModule("4ad810b2-9714-496d-beec-970ef601e9e2", ModuleType.Recording, 1)]
    public partial class Change_name_and_surname : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Licenta_NohaiRepository repository.
        /// </summary>
        public static Licenta_NohaiRepository repo = Licenta_NohaiRepository.Instance;

        static Change_name_and_surname instance = new Change_name_and_surname();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Change_name_and_surname()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Change_name_and_surname Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.AccountMenu' at Center.", repo.ApplicationUnderTest.AccountMenuInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.AccountMenu.Click();
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Setări' at Center.", repo.ApplicationUnderTest.SetăriInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.Setări.Click();
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.FirstName' at Center.", repo.ApplicationUnderTest.FirstNameInfo, new RecordItemIndex(2));
            //repo.ApplicationUnderTest.FirstName.Click();
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Dragos' with focus on 'ApplicationUnderTest.FirstName'.", repo.ApplicationUnderTest.FirstNameInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.FirstName.PressKeys("Dragos");
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.LastName' at Center.", repo.ApplicationUnderTest.LastNameInfo, new RecordItemIndex(4));
            //repo.ApplicationUnderTest.LastName.Click();
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'NOhai' with focus on 'ApplicationUnderTest.LastName'.", repo.ApplicationUnderTest.LastNameInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.LastName.PressKeys("NOhai");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.CardJhCard.Salvare1' at Center.", repo.ApplicationUnderTest.CardJhCard.Salvare1Info, new RecordItemIndex(6));
            repo.ApplicationUnderTest.CardJhCard.Salvare1.Click();
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ApplicationUnderTest.CardJhCard.AlertAlertSuccess'.", repo.ApplicationUnderTest.CardJhCard.AlertAlertSuccessInfo, new RecordItemIndex(7));
            Validate.Exists(repo.ApplicationUnderTest.CardJhCard.AlertAlertSuccessInfo);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
