///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Licenta_Nohai
{
    public partial class Delete_data_from_student
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void Mouse_Click_JhiConfirmDeleteStudent(RepoItemInfo buttontagInfo)
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'buttontagInfo' at 121;39.", buttontagInfo);
            buttontagInfo.FindAdapter<ButtonTag>().Click("121;39");
        }

        public void Mouse_Click_BtnBtnDangerBtnSm(RepoItemInfo buttontagInfo)
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'buttontagInfo' at 72;17.", buttontagInfo);
            buttontagInfo.FindAdapter<ButtonTag>().Click("72;17");
        }

    }
}
