///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Licenta_Nohai
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Licenta_NohaiRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("940bae96-c8f7-487f-bbcd-0944a724c83b")]
    public partial class Licenta_NohaiRepository : RepoGenBaseFolder
    {
        static Licenta_NohaiRepository instance = new Licenta_NohaiRepository();
        Licenta_NohaiRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        Licenta_NohaiRepositoryFolders.DropdownAppFolder _dropdown;

        /// <summary>
        /// Gets the singleton class instance representing the Licenta_NohaiRepository element repository.
        /// </summary>
        [RepositoryFolder("940bae96-c8f7-487f-bbcd-0944a724c83b")]
        public static Licenta_NohaiRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Licenta_NohaiRepository() 
            : base("Licenta_NohaiRepository", "/", null, 0, false, "940bae96-c8f7-487f-bbcd-0944a724c83b", ".\\RepositoryImages\\Licenta_NohaiRepository940bae96.rximgres")
        {
            _applicationundertest = new Licenta_NohaiRepositoryFolders.ApplicationUnderTestAppFolder(this);
            _dropdown = new Licenta_NohaiRepositoryFolders.DropdownAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("940bae96-c8f7-487f-bbcd-0944a724c83b")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("a7205831-1ecb-405e-9044-28c1388bf99a")]
        public virtual Licenta_NohaiRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The Dropdown folder.
        /// </summary>
        [RepositoryFolder("718c5e3b-9139-43f7-88f0-3a761798ba93")]
        public virtual Licenta_NohaiRepositoryFolders.DropdownAppFolder Dropdown
        {
            get { return _dropdown; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class Licenta_NohaiRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("a7205831-1ecb-405e-9044-28c1388bf99a")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            Licenta_NohaiRepositoryFolders.CardJhCardFolder _cardjhcard;
            Licenta_NohaiRepositoryFolders.ContainerFluidFolder _containerfluid;
            RepoItemInfo _accountmenuInfo;
            RepoItemInfo _logoutInfo;
            RepoItemInfo _passwordInfo;
            RepoItemInfo _usernameInfo;
            RepoItemInfo _bineaivenitinaplicațiadetestareInfo;
            RepoItemInfo _loginInfo;
            RepoItemInfo _remembermeInfo;
            RepoItemInfo _autentificareInfo;
            RepoItemInfo _homeloggedmessageInfo;
            RepoItemInfo _emailInfo;
            RepoItemInfo _confirmpasswordInfo;
            RepoItemInfo _autentificare1Info;
            RepoItemInfo _adminmenuInfo;
            RepoItemInfo _gestiuneutilizatoriInfo;
            RepoItemInfo _pathInfo;
            RepoItemInfo _setăriInfo;
            RepoItemInfo _firstnameInfo;
            RepoItemInfo _lastnameInfo;
            RepoItemInfo _entitymenuInfo;
            RepoItemInfo _departamentInfo;
            RepoItemInfo _jhcreateentityInfo;
            RepoItemInfo _fieldnumedepartamentInfo;
            RepoItemInfo _salvareInfo;
            RepoItemInfo _tabeleInfo;
            RepoItemInfo _programstudiuInfo;
            RepoItemInfo _creareprogramstudiuInfo;
            RepoItemInfo _fieldprogramInfo;
            RepoItemInfo _fielddepartamentInfo;
            RepoItemInfo _cadrudidacticInfo;
            RepoItemInfo _crearecadrudidacticInfo;
            RepoItemInfo _fieldnumeInfo;
            RepoItemInfo _fieldprenumeInfo;
            RepoItemInfo _fieldtitluInfo;
            RepoItemInfo _fieldemailInfo;
            RepoItemInfo _fieldbirouInfo;
            RepoItemInfo _studentInfo;
            RepoItemInfo _fieldnumarmatricolInfo;
            RepoItemInfo _fieldlucrarelicentaInfo;
            RepoItemInfo _fieldliniaInfo;
            RepoItemInfo _fieldformaInfo;
            RepoItemInfo _fieldcadrudidacticInfo;
            RepoItemInfo _jhiconfirmdeletestudentInfo;
            RepoItemInfo _ștergereInfo;
            RepoItemInfo _jhiconfirmdeletecadrudidacticInfo;
            RepoItemInfo _jhiconfirmdeleteprogramstudiuInfo;
            RepoItemInfo _jhiconfirmdeletedepartamentInfo;
            RepoItemInfo _btnbtndangerInfo;
            RepoItemInfo _password1Info;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='192.168.1.4:8080']", parentFolder, 30000, null, false, "a7205831-1ecb-405e-9044-28c1388bf99a", "")
            {
                _cardjhcard = new Licenta_NohaiRepositoryFolders.CardJhCardFolder(this);
                _containerfluid = new Licenta_NohaiRepositoryFolders.ContainerFluidFolder(this);
                _accountmenuInfo = new RepoItemInfo(this, "AccountMenu", ".//a[#'account-menu']", 30000, null, "8a8e12de-ebaa-4e7a-bf73-e47dd9f62aad");
                _logoutInfo = new RepoItemInfo(this, "Logout", ".//a[#'logout']", 30000, null, "37fad78d-9660-4874-adbe-56eeb9e7a3b4");
                _passwordInfo = new RepoItemInfo(this, "Password", "body/tag[@tagname='ngb-modal-window']/div/div//input[#'password']", 30000, null, "603c9165-53b0-470e-86e8-aab459013c2e");
                _usernameInfo = new RepoItemInfo(this, "Username", "body/tag[@tagname='ngb-modal-window']/div/div//input[#'username']", 30000, null, "86a7e05f-9e4f-46ca-8bfc-dd06abade01e");
                _bineaivenitinaplicațiadetestareInfo = new RepoItemInfo(this, "BineAiVenitInAplicațiaDeTestare", "body/tag[@tagname='jhi-main']/div[2]/div//h1[@innertext>'Bine ai venit în aplicația']", 30000, null, "05bd3ef4-613e-4152-86e1-437023c8d023");
                _loginInfo = new RepoItemInfo(this, "Login", ".//a[#'login']", 30000, null, "5a5fc2af-bba1-4782-84b9-55e1da82db5b");
                _remembermeInfo = new RepoItemInfo(this, "RememberMe", ".//input[#'rememberMe']", 30000, null, "6f4992e7-cdaa-4eae-a933-cfbc9aef80b4");
                _autentificareInfo = new RepoItemInfo(this, "Autentificare", "body//tag[@tagname='jhi-login-modal']/div[2]/div/div[2]/form[@action='http://192.168.1.4:8080/']/button[@innertext='Autentificare']", 30000, null, "47873e3e-6467-4b69-bf14-6b7b0eafce38");
                _homeloggedmessageInfo = new RepoItemInfo(this, "HomeLoggedMessage", ".//span[#'home-logged-message']", 30000, null, "a4f9b977-3388-42d8-8fba-3d4e80af64ff");
                _emailInfo = new RepoItemInfo(this, "Email", ".//input[#'email']", 30000, null, "8af6e430-6854-47e5-917a-72379b7a2f72");
                _confirmpasswordInfo = new RepoItemInfo(this, "ConfirmPassword", ".//input[#'confirmPassword']", 30000, null, "7703dd79-9619-4a5c-b2cf-21ffec2edd2e");
                _autentificare1Info = new RepoItemInfo(this, "Autentificare1", "body//tag[@tagname='jhi-login-modal']/div[2]/div/div[2]/form[@action='http://192.168.1.4:8080/register']/button[@innertext='Autentificare']", 30000, null, "d13db929-0da5-4d80-9434-b8b80efa20e3");
                _adminmenuInfo = new RepoItemInfo(this, "AdminMenu", ".//a[#'admin-menu']", 30000, null, "27b5aa56-634b-453e-a8f6-b3ee87b0d686");
                _gestiuneutilizatoriInfo = new RepoItemInfo(this, "GestiuneUtilizatori", ".//div[#'navbarResponsive']/ul/li[3]/ul//span[@innertext='Gestiune utilizatori']", 30000, null, "e2eae079-ce5b-40d7-be60-8d593b8f54ea");
                _pathInfo = new RepoItemInfo(this, "Path", ".//a[#'logout']//tag[@tagname='path']", 30000, null, "07fce621-cf7c-4e11-918c-96b82ec327bf");
                _setăriInfo = new RepoItemInfo(this, "Setări", ".//div[#'navbarResponsive']/ul/li[4]/ul//span[@innertext='Setări']", 30000, null, "e28f1ce3-3479-4778-bda4-c60f5573cdfa");
                _firstnameInfo = new RepoItemInfo(this, "FirstName", ".//input[#'firstName']", 30000, null, "bf24efa0-2efc-43e3-8aed-6d1b19316ed6");
                _lastnameInfo = new RepoItemInfo(this, "LastName", ".//input[#'lastName']", 30000, null, "c89574c2-2805-416c-8df2-d1dcca121645");
                _entitymenuInfo = new RepoItemInfo(this, "EntityMenu", ".//a[#'entity-menu']", 30000, null, "ae889971-4b6b-407e-811c-9b2e878544ca");
                _departamentInfo = new RepoItemInfo(this, "Departament", ".//div[#'navbarResponsive']/ul/?/?/ul//span[@innertext='Departament']", 30000, null, "375c5537-2b7d-4580-b1e2-b5530675bb96");
                _jhcreateentityInfo = new RepoItemInfo(this, "JhCreateEntity", ".//button[#'jh-create-entity']", 30000, null, "2f5eccb7-4008-47c6-b5b6-bcb88daba52f");
                _fieldnumedepartamentInfo = new RepoItemInfo(this, "FieldNumeDepartament", ".//input[#'field_numeDepartament']", 30000, null, "580e1803-ddf7-4bbf-a952-b89c6e5e189a");
                _salvareInfo = new RepoItemInfo(this, "Salvare", ".//button[#'save-entity']/span[@innertext='Salvare']", 30000, null, "5f680d0c-dc68-441b-95ac-a6af97ca279c");
                _tabeleInfo = new RepoItemInfo(this, "Tabele", ".//a[#'entity-menu']/?/?/span[@innertext='Tabele']", 30000, null, "c6cd0d6d-460b-4fd0-be6f-455a1b6963f0");
                _programstudiuInfo = new RepoItemInfo(this, "ProgramStudiu", ".//div[#'navbarResponsive']/ul/?/?/ul//span[@innertext='Program studiu']", 30000, null, "648ab967-d7de-4ccf-9628-47277884c8c9");
                _creareprogramstudiuInfo = new RepoItemInfo(this, "CreareProgramStudiu", ".//button[#'jh-create-entity']/span[@innertext='Creare program studiu']", 30000, null, "29f0f569-7959-42cd-9388-b0a58e4b47f6");
                _fieldprogramInfo = new RepoItemInfo(this, "FieldProgram", ".//input[#'field_program']", 30000, null, "8ab730ef-b70d-47a9-9519-4febf30a3191");
                _fielddepartamentInfo = new RepoItemInfo(this, "FieldDepartament", ".//select[#'field_departament']", 30000, null, "b6b313d1-8a1b-4dc0-8dd0-5eccffc171cf");
                _cadrudidacticInfo = new RepoItemInfo(this, "CadruDidactic", ".//div[#'navbarResponsive']/ul/?/?/ul//span[@innertext='Cadru didactic']", 30000, null, "fd654640-38f1-4619-af78-5d374dae140f");
                _crearecadrudidacticInfo = new RepoItemInfo(this, "CreareCadruDidactic", ".//button[#'jh-create-entity']/span[@innertext='Creare cadru didactic']", 30000, null, "2aea559b-566e-4906-9c3a-b0f31599338c");
                _fieldnumeInfo = new RepoItemInfo(this, "FieldNume", ".//input[#'field_nume']", 30000, null, "080bb4e9-e9d6-43a2-8a8f-cb4df55ff2fe");
                _fieldprenumeInfo = new RepoItemInfo(this, "FieldPrenume", ".//input[#'field_prenume']", 30000, null, "f53d1a8f-53ea-4338-8141-68f344c126fa");
                _fieldtitluInfo = new RepoItemInfo(this, "FieldTitlu", ".//input[#'field_titlu']", 30000, null, "723bbf00-d9a7-420a-8ae0-374ddb9eddfe");
                _fieldemailInfo = new RepoItemInfo(this, "FieldEmail", ".//input[#'field_email']", 30000, null, "d331ce78-1d1f-4b7e-855b-149bae7267de");
                _fieldbirouInfo = new RepoItemInfo(this, "FieldBirou", ".//input[#'field_birou']", 30000, null, "b8f8660f-0f80-429b-8d3e-28497030d2a4");
                _studentInfo = new RepoItemInfo(this, "Student", ".//div[#'navbarResponsive']/ul/?/?/ul//span[@innertext='Student']", 30000, null, "b3cf6827-8d1c-4428-a19a-9b21799bcc66");
                _fieldnumarmatricolInfo = new RepoItemInfo(this, "FieldNumarMatricol", ".//input[#'field_numarMatricol']", 30000, null, "255fcd87-712b-4c9f-a4ac-8628dda6b7cc");
                _fieldlucrarelicentaInfo = new RepoItemInfo(this, "FieldLucrareLicenta", ".//input[#'field_lucrareLicenta']", 30000, null, "ba831c4f-22b0-4087-8c9d-b4571d14c7bb");
                _fieldliniaInfo = new RepoItemInfo(this, "FieldLinia", ".//select[#'field_linia']", 30000, null, "29f067fc-4a7b-4817-abd8-aecd9ec0c176");
                _fieldformaInfo = new RepoItemInfo(this, "FieldForma", ".//select[#'field_forma']", 3000, null, "e6e95769-d406-4fd0-ae98-a21ca99c8d38");
                _fieldcadrudidacticInfo = new RepoItemInfo(this, "FieldCadruDidactic", ".//select[#'field_cadruDidactic']", 30000, null, "a926d200-3240-4965-8e8c-7723e5e22958");
                _jhiconfirmdeletestudentInfo = new RepoItemInfo(this, "JhiConfirmDeleteStudent", ".//button[#'jhi-confirm-delete-student']", 30000, null, "ec6d5931-482f-4e69-9fb2-bcb0493c2b46");
                _ștergereInfo = new RepoItemInfo(this, "Ștergere", ".//button[#'jhi-confirm-delete-student']/span[@innertext='Ștergere']", 30000, null, "39379724-86b8-4e47-abde-5e66a74317cc");
                _jhiconfirmdeletecadrudidacticInfo = new RepoItemInfo(this, "JhiConfirmDeleteCadruDidactic", ".//button[#'jhi-confirm-delete-cadruDidactic']", 30000, null, "159cc891-ca22-4988-bea6-d0b9f51e37f2");
                _jhiconfirmdeleteprogramstudiuInfo = new RepoItemInfo(this, "JhiConfirmDeleteProgramStudiu", ".//button[#'jhi-confirm-delete-programStudiu']", 30000, null, "fba45fcd-e0ab-4391-ab06-863dbda8325f");
                _jhiconfirmdeletedepartamentInfo = new RepoItemInfo(this, "JhiConfirmDeleteDepartament", ".//button[#'jhi-confirm-delete-departament']", 30000, null, "1d998b2f-319c-48b6-9c9c-f523f33be1e3");
                _btnbtndangerInfo = new RepoItemInfo(this, "BtnBtnDanger", "body//form[@name='deleteForm']/div[3]/button[2]", 30000, null, "5711b431-9146-4249-8780-183b80f3b236");
                _password1Info = new RepoItemInfo(this, "Password1", ".//input[#'password']", 30000, null, "6d6bcfed-2ad7-4383-882c-5cf5c19a7541");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a7205831-1ecb-405e-9044-28c1388bf99a")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a7205831-1ecb-405e-9044-28c1388bf99a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The AccountMenu item.
            /// </summary>
            [RepositoryItem("8a8e12de-ebaa-4e7a-bf73-e47dd9f62aad")]
            public virtual Ranorex.ATag AccountMenu
            {
                get
                {
                    return _accountmenuInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The AccountMenu item info.
            /// </summary>
            [RepositoryItemInfo("8a8e12de-ebaa-4e7a-bf73-e47dd9f62aad")]
            public virtual RepoItemInfo AccountMenuInfo
            {
                get
                {
                    return _accountmenuInfo;
                }
            }

            /// <summary>
            /// The Logout item.
            /// </summary>
            [RepositoryItem("37fad78d-9660-4874-adbe-56eeb9e7a3b4")]
            public virtual Ranorex.ATag Logout
            {
                get
                {
                    return _logoutInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Logout item info.
            /// </summary>
            [RepositoryItemInfo("37fad78d-9660-4874-adbe-56eeb9e7a3b4")]
            public virtual RepoItemInfo LogoutInfo
            {
                get
                {
                    return _logoutInfo;
                }
            }

            /// <summary>
            /// The Password item.
            /// </summary>
            [RepositoryItem("603c9165-53b0-470e-86e8-aab459013c2e")]
            public virtual Ranorex.InputTag Password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Password item info.
            /// </summary>
            [RepositoryItemInfo("603c9165-53b0-470e-86e8-aab459013c2e")]
            public virtual RepoItemInfo PasswordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }

            /// <summary>
            /// The Username item.
            /// </summary>
            [RepositoryItem("86a7e05f-9e4f-46ca-8bfc-dd06abade01e")]
            public virtual Ranorex.InputTag Username
            {
                get
                {
                    return _usernameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Username item info.
            /// </summary>
            [RepositoryItemInfo("86a7e05f-9e4f-46ca-8bfc-dd06abade01e")]
            public virtual RepoItemInfo UsernameInfo
            {
                get
                {
                    return _usernameInfo;
                }
            }

            /// <summary>
            /// The BineAiVenitInAplicațiaDeTestare item.
            /// </summary>
            [RepositoryItem("05bd3ef4-613e-4152-86e1-437023c8d023")]
            public virtual Ranorex.H1Tag BineAiVenitInAplicațiaDeTestare
            {
                get
                {
                    return _bineaivenitinaplicațiadetestareInfo.CreateAdapter<Ranorex.H1Tag>(true);
                }
            }

            /// <summary>
            /// The BineAiVenitInAplicațiaDeTestare item info.
            /// </summary>
            [RepositoryItemInfo("05bd3ef4-613e-4152-86e1-437023c8d023")]
            public virtual RepoItemInfo BineAiVenitInAplicațiaDeTestareInfo
            {
                get
                {
                    return _bineaivenitinaplicațiadetestareInfo;
                }
            }

            /// <summary>
            /// The Login item.
            /// </summary>
            [RepositoryItem("5a5fc2af-bba1-4782-84b9-55e1da82db5b")]
            public virtual Ranorex.ATag Login
            {
                get
                {
                    return _loginInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Login item info.
            /// </summary>
            [RepositoryItemInfo("5a5fc2af-bba1-4782-84b9-55e1da82db5b")]
            public virtual RepoItemInfo LoginInfo
            {
                get
                {
                    return _loginInfo;
                }
            }

            /// <summary>
            /// The RememberMe item.
            /// </summary>
            [RepositoryItem("6f4992e7-cdaa-4eae-a933-cfbc9aef80b4")]
            public virtual Ranorex.InputTag RememberMe
            {
                get
                {
                    return _remembermeInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The RememberMe item info.
            /// </summary>
            [RepositoryItemInfo("6f4992e7-cdaa-4eae-a933-cfbc9aef80b4")]
            public virtual RepoItemInfo RememberMeInfo
            {
                get
                {
                    return _remembermeInfo;
                }
            }

            /// <summary>
            /// The Autentificare item.
            /// </summary>
            [RepositoryItem("47873e3e-6467-4b69-bf14-6b7b0eafce38")]
            public virtual Ranorex.ButtonTag Autentificare
            {
                get
                {
                    return _autentificareInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The Autentificare item info.
            /// </summary>
            [RepositoryItemInfo("47873e3e-6467-4b69-bf14-6b7b0eafce38")]
            public virtual RepoItemInfo AutentificareInfo
            {
                get
                {
                    return _autentificareInfo;
                }
            }

            /// <summary>
            /// The HomeLoggedMessage item.
            /// </summary>
            [RepositoryItem("a4f9b977-3388-42d8-8fba-3d4e80af64ff")]
            public virtual Ranorex.SpanTag HomeLoggedMessage
            {
                get
                {
                    return _homeloggedmessageInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The HomeLoggedMessage item info.
            /// </summary>
            [RepositoryItemInfo("a4f9b977-3388-42d8-8fba-3d4e80af64ff")]
            public virtual RepoItemInfo HomeLoggedMessageInfo
            {
                get
                {
                    return _homeloggedmessageInfo;
                }
            }

            /// <summary>
            /// The Email item.
            /// </summary>
            [RepositoryItem("8af6e430-6854-47e5-917a-72379b7a2f72")]
            public virtual Ranorex.InputTag Email
            {
                get
                {
                    return _emailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Email item info.
            /// </summary>
            [RepositoryItemInfo("8af6e430-6854-47e5-917a-72379b7a2f72")]
            public virtual RepoItemInfo EmailInfo
            {
                get
                {
                    return _emailInfo;
                }
            }

            /// <summary>
            /// The ConfirmPassword item.
            /// </summary>
            [RepositoryItem("7703dd79-9619-4a5c-b2cf-21ffec2edd2e")]
            public virtual Ranorex.InputTag ConfirmPassword
            {
                get
                {
                    return _confirmpasswordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The ConfirmPassword item info.
            /// </summary>
            [RepositoryItemInfo("7703dd79-9619-4a5c-b2cf-21ffec2edd2e")]
            public virtual RepoItemInfo ConfirmPasswordInfo
            {
                get
                {
                    return _confirmpasswordInfo;
                }
            }

            /// <summary>
            /// The Autentificare1 item.
            /// </summary>
            [RepositoryItem("d13db929-0da5-4d80-9434-b8b80efa20e3")]
            public virtual Ranorex.ButtonTag Autentificare1
            {
                get
                {
                    return _autentificare1Info.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The Autentificare1 item info.
            /// </summary>
            [RepositoryItemInfo("d13db929-0da5-4d80-9434-b8b80efa20e3")]
            public virtual RepoItemInfo Autentificare1Info
            {
                get
                {
                    return _autentificare1Info;
                }
            }

            /// <summary>
            /// The AdminMenu item.
            /// </summary>
            [RepositoryItem("27b5aa56-634b-453e-a8f6-b3ee87b0d686")]
            public virtual Ranorex.ATag AdminMenu
            {
                get
                {
                    return _adminmenuInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The AdminMenu item info.
            /// </summary>
            [RepositoryItemInfo("27b5aa56-634b-453e-a8f6-b3ee87b0d686")]
            public virtual RepoItemInfo AdminMenuInfo
            {
                get
                {
                    return _adminmenuInfo;
                }
            }

            /// <summary>
            /// The GestiuneUtilizatori item.
            /// </summary>
            [RepositoryItem("e2eae079-ce5b-40d7-be60-8d593b8f54ea")]
            public virtual Ranorex.SpanTag GestiuneUtilizatori
            {
                get
                {
                    return _gestiuneutilizatoriInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The GestiuneUtilizatori item info.
            /// </summary>
            [RepositoryItemInfo("e2eae079-ce5b-40d7-be60-8d593b8f54ea")]
            public virtual RepoItemInfo GestiuneUtilizatoriInfo
            {
                get
                {
                    return _gestiuneutilizatoriInfo;
                }
            }

            /// <summary>
            /// The Path item.
            /// </summary>
            [RepositoryItem("07fce621-cf7c-4e11-918c-96b82ec327bf")]
            public virtual Ranorex.WebElement Path
            {
                get
                {
                    return _pathInfo.CreateAdapter<Ranorex.WebElement>(true);
                }
            }

            /// <summary>
            /// The Path item info.
            /// </summary>
            [RepositoryItemInfo("07fce621-cf7c-4e11-918c-96b82ec327bf")]
            public virtual RepoItemInfo PathInfo
            {
                get
                {
                    return _pathInfo;
                }
            }

            /// <summary>
            /// The Setări item.
            /// </summary>
            [RepositoryItem("e28f1ce3-3479-4778-bda4-c60f5573cdfa")]
            public virtual Ranorex.SpanTag Setări
            {
                get
                {
                    return _setăriInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Setări item info.
            /// </summary>
            [RepositoryItemInfo("e28f1ce3-3479-4778-bda4-c60f5573cdfa")]
            public virtual RepoItemInfo SetăriInfo
            {
                get
                {
                    return _setăriInfo;
                }
            }

            /// <summary>
            /// The FirstName item.
            /// </summary>
            [RepositoryItem("bf24efa0-2efc-43e3-8aed-6d1b19316ed6")]
            public virtual Ranorex.InputTag FirstName
            {
                get
                {
                    return _firstnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The FirstName item info.
            /// </summary>
            [RepositoryItemInfo("bf24efa0-2efc-43e3-8aed-6d1b19316ed6")]
            public virtual RepoItemInfo FirstNameInfo
            {
                get
                {
                    return _firstnameInfo;
                }
            }

            /// <summary>
            /// The LastName item.
            /// </summary>
            [RepositoryItem("c89574c2-2805-416c-8df2-d1dcca121645")]
            public virtual Ranorex.InputTag LastName
            {
                get
                {
                    return _lastnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LastName item info.
            /// </summary>
            [RepositoryItemInfo("c89574c2-2805-416c-8df2-d1dcca121645")]
            public virtual RepoItemInfo LastNameInfo
            {
                get
                {
                    return _lastnameInfo;
                }
            }

            /// <summary>
            /// The EntityMenu item.
            /// </summary>
            [RepositoryItem("ae889971-4b6b-407e-811c-9b2e878544ca")]
            public virtual Ranorex.ATag EntityMenu
            {
                get
                {
                    return _entitymenuInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The EntityMenu item info.
            /// </summary>
            [RepositoryItemInfo("ae889971-4b6b-407e-811c-9b2e878544ca")]
            public virtual RepoItemInfo EntityMenuInfo
            {
                get
                {
                    return _entitymenuInfo;
                }
            }

            /// <summary>
            /// The Departament item.
            /// </summary>
            [RepositoryItem("375c5537-2b7d-4580-b1e2-b5530675bb96")]
            public virtual Ranorex.SpanTag Departament
            {
                get
                {
                    return _departamentInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Departament item info.
            /// </summary>
            [RepositoryItemInfo("375c5537-2b7d-4580-b1e2-b5530675bb96")]
            public virtual RepoItemInfo DepartamentInfo
            {
                get
                {
                    return _departamentInfo;
                }
            }

            /// <summary>
            /// The JhCreateEntity item.
            /// </summary>
            [RepositoryItem("2f5eccb7-4008-47c6-b5b6-bcb88daba52f")]
            public virtual Ranorex.ButtonTag JhCreateEntity
            {
                get
                {
                    return _jhcreateentityInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The JhCreateEntity item info.
            /// </summary>
            [RepositoryItemInfo("2f5eccb7-4008-47c6-b5b6-bcb88daba52f")]
            public virtual RepoItemInfo JhCreateEntityInfo
            {
                get
                {
                    return _jhcreateentityInfo;
                }
            }

            /// <summary>
            /// The FieldNumeDepartament item.
            /// </summary>
            [RepositoryItem("580e1803-ddf7-4bbf-a952-b89c6e5e189a")]
            public virtual Ranorex.InputTag FieldNumeDepartament
            {
                get
                {
                    return _fieldnumedepartamentInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The FieldNumeDepartament item info.
            /// </summary>
            [RepositoryItemInfo("580e1803-ddf7-4bbf-a952-b89c6e5e189a")]
            public virtual RepoItemInfo FieldNumeDepartamentInfo
            {
                get
                {
                    return _fieldnumedepartamentInfo;
                }
            }

            /// <summary>
            /// The Salvare item.
            /// </summary>
            [RepositoryItem("5f680d0c-dc68-441b-95ac-a6af97ca279c")]
            public virtual Ranorex.SpanTag Salvare
            {
                get
                {
                    return _salvareInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Salvare item info.
            /// </summary>
            [RepositoryItemInfo("5f680d0c-dc68-441b-95ac-a6af97ca279c")]
            public virtual RepoItemInfo SalvareInfo
            {
                get
                {
                    return _salvareInfo;
                }
            }

            /// <summary>
            /// The Tabele item.
            /// </summary>
            [RepositoryItem("c6cd0d6d-460b-4fd0-be6f-455a1b6963f0")]
            public virtual Ranorex.SpanTag Tabele
            {
                get
                {
                    return _tabeleInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Tabele item info.
            /// </summary>
            [RepositoryItemInfo("c6cd0d6d-460b-4fd0-be6f-455a1b6963f0")]
            public virtual RepoItemInfo TabeleInfo
            {
                get
                {
                    return _tabeleInfo;
                }
            }

            /// <summary>
            /// The ProgramStudiu item.
            /// </summary>
            [RepositoryItem("648ab967-d7de-4ccf-9628-47277884c8c9")]
            public virtual Ranorex.SpanTag ProgramStudiu
            {
                get
                {
                    return _programstudiuInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The ProgramStudiu item info.
            /// </summary>
            [RepositoryItemInfo("648ab967-d7de-4ccf-9628-47277884c8c9")]
            public virtual RepoItemInfo ProgramStudiuInfo
            {
                get
                {
                    return _programstudiuInfo;
                }
            }

            /// <summary>
            /// The CreareProgramStudiu item.
            /// </summary>
            [RepositoryItem("29f0f569-7959-42cd-9388-b0a58e4b47f6")]
            public virtual Ranorex.SpanTag CreareProgramStudiu
            {
                get
                {
                    return _creareprogramstudiuInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The CreareProgramStudiu item info.
            /// </summary>
            [RepositoryItemInfo("29f0f569-7959-42cd-9388-b0a58e4b47f6")]
            public virtual RepoItemInfo CreareProgramStudiuInfo
            {
                get
                {
                    return _creareprogramstudiuInfo;
                }
            }

            /// <summary>
            /// The FieldProgram item.
            /// </summary>
            [RepositoryItem("8ab730ef-b70d-47a9-9519-4febf30a3191")]
            public virtual Ranorex.InputTag FieldProgram
            {
                get
                {
                    return _fieldprogramInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The FieldProgram item info.
            /// </summary>
            [RepositoryItemInfo("8ab730ef-b70d-47a9-9519-4febf30a3191")]
            public virtual RepoItemInfo FieldProgramInfo
            {
                get
                {
                    return _fieldprogramInfo;
                }
            }

            /// <summary>
            /// The FieldDepartament item.
            /// </summary>
            [RepositoryItem("b6b313d1-8a1b-4dc0-8dd0-5eccffc171cf")]
            public virtual Ranorex.SelectTag FieldDepartament
            {
                get
                {
                    return _fielddepartamentInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The FieldDepartament item info.
            /// </summary>
            [RepositoryItemInfo("b6b313d1-8a1b-4dc0-8dd0-5eccffc171cf")]
            public virtual RepoItemInfo FieldDepartamentInfo
            {
                get
                {
                    return _fielddepartamentInfo;
                }
            }

            /// <summary>
            /// The CadruDidactic item.
            /// </summary>
            [RepositoryItem("fd654640-38f1-4619-af78-5d374dae140f")]
            public virtual Ranorex.SpanTag CadruDidactic
            {
                get
                {
                    return _cadrudidacticInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The CadruDidactic item info.
            /// </summary>
            [RepositoryItemInfo("fd654640-38f1-4619-af78-5d374dae140f")]
            public virtual RepoItemInfo CadruDidacticInfo
            {
                get
                {
                    return _cadrudidacticInfo;
                }
            }

            /// <summary>
            /// The CreareCadruDidactic item.
            /// </summary>
            [RepositoryItem("2aea559b-566e-4906-9c3a-b0f31599338c")]
            public virtual Ranorex.SpanTag CreareCadruDidactic
            {
                get
                {
                    return _crearecadrudidacticInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The CreareCadruDidactic item info.
            /// </summary>
            [RepositoryItemInfo("2aea559b-566e-4906-9c3a-b0f31599338c")]
            public virtual RepoItemInfo CreareCadruDidacticInfo
            {
                get
                {
                    return _crearecadrudidacticInfo;
                }
            }

            /// <summary>
            /// The FieldNume item.
            /// </summary>
            [RepositoryItem("080bb4e9-e9d6-43a2-8a8f-cb4df55ff2fe")]
            public virtual Ranorex.InputTag FieldNume
            {
                get
                {
                    return _fieldnumeInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The FieldNume item info.
            /// </summary>
            [RepositoryItemInfo("080bb4e9-e9d6-43a2-8a8f-cb4df55ff2fe")]
            public virtual RepoItemInfo FieldNumeInfo
            {
                get
                {
                    return _fieldnumeInfo;
                }
            }

            /// <summary>
            /// The FieldPrenume item.
            /// </summary>
            [RepositoryItem("f53d1a8f-53ea-4338-8141-68f344c126fa")]
            public virtual Ranorex.InputTag FieldPrenume
            {
                get
                {
                    return _fieldprenumeInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The FieldPrenume item info.
            /// </summary>
            [RepositoryItemInfo("f53d1a8f-53ea-4338-8141-68f344c126fa")]
            public virtual RepoItemInfo FieldPrenumeInfo
            {
                get
                {
                    return _fieldprenumeInfo;
                }
            }

            /// <summary>
            /// The FieldTitlu item.
            /// </summary>
            [RepositoryItem("723bbf00-d9a7-420a-8ae0-374ddb9eddfe")]
            public virtual Ranorex.InputTag FieldTitlu
            {
                get
                {
                    return _fieldtitluInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The FieldTitlu item info.
            /// </summary>
            [RepositoryItemInfo("723bbf00-d9a7-420a-8ae0-374ddb9eddfe")]
            public virtual RepoItemInfo FieldTitluInfo
            {
                get
                {
                    return _fieldtitluInfo;
                }
            }

            /// <summary>
            /// The FieldEmail item.
            /// </summary>
            [RepositoryItem("d331ce78-1d1f-4b7e-855b-149bae7267de")]
            public virtual Ranorex.InputTag FieldEmail
            {
                get
                {
                    return _fieldemailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The FieldEmail item info.
            /// </summary>
            [RepositoryItemInfo("d331ce78-1d1f-4b7e-855b-149bae7267de")]
            public virtual RepoItemInfo FieldEmailInfo
            {
                get
                {
                    return _fieldemailInfo;
                }
            }

            /// <summary>
            /// The FieldBirou item.
            /// </summary>
            [RepositoryItem("b8f8660f-0f80-429b-8d3e-28497030d2a4")]
            public virtual Ranorex.InputTag FieldBirou
            {
                get
                {
                    return _fieldbirouInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The FieldBirou item info.
            /// </summary>
            [RepositoryItemInfo("b8f8660f-0f80-429b-8d3e-28497030d2a4")]
            public virtual RepoItemInfo FieldBirouInfo
            {
                get
                {
                    return _fieldbirouInfo;
                }
            }

            /// <summary>
            /// The Student item.
            /// </summary>
            [RepositoryItem("b3cf6827-8d1c-4428-a19a-9b21799bcc66")]
            public virtual Ranorex.SpanTag Student
            {
                get
                {
                    return _studentInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Student item info.
            /// </summary>
            [RepositoryItemInfo("b3cf6827-8d1c-4428-a19a-9b21799bcc66")]
            public virtual RepoItemInfo StudentInfo
            {
                get
                {
                    return _studentInfo;
                }
            }

            /// <summary>
            /// The FieldNumarMatricol item.
            /// </summary>
            [RepositoryItem("255fcd87-712b-4c9f-a4ac-8628dda6b7cc")]
            public virtual Ranorex.InputTag FieldNumarMatricol
            {
                get
                {
                    return _fieldnumarmatricolInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The FieldNumarMatricol item info.
            /// </summary>
            [RepositoryItemInfo("255fcd87-712b-4c9f-a4ac-8628dda6b7cc")]
            public virtual RepoItemInfo FieldNumarMatricolInfo
            {
                get
                {
                    return _fieldnumarmatricolInfo;
                }
            }

            /// <summary>
            /// The FieldLucrareLicenta item.
            /// </summary>
            [RepositoryItem("ba831c4f-22b0-4087-8c9d-b4571d14c7bb")]
            public virtual Ranorex.InputTag FieldLucrareLicenta
            {
                get
                {
                    return _fieldlucrarelicentaInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The FieldLucrareLicenta item info.
            /// </summary>
            [RepositoryItemInfo("ba831c4f-22b0-4087-8c9d-b4571d14c7bb")]
            public virtual RepoItemInfo FieldLucrareLicentaInfo
            {
                get
                {
                    return _fieldlucrarelicentaInfo;
                }
            }

            /// <summary>
            /// The FieldLinia item.
            /// </summary>
            [RepositoryItem("29f067fc-4a7b-4817-abd8-aecd9ec0c176")]
            public virtual Ranorex.SelectTag FieldLinia
            {
                get
                {
                    return _fieldliniaInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The FieldLinia item info.
            /// </summary>
            [RepositoryItemInfo("29f067fc-4a7b-4817-abd8-aecd9ec0c176")]
            public virtual RepoItemInfo FieldLiniaInfo
            {
                get
                {
                    return _fieldliniaInfo;
                }
            }

            /// <summary>
            /// The FieldForma item.
            /// </summary>
            [RepositoryItem("e6e95769-d406-4fd0-ae98-a21ca99c8d38")]
            public virtual Ranorex.SelectTag FieldForma
            {
                get
                {
                    return _fieldformaInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The FieldForma item info.
            /// </summary>
            [RepositoryItemInfo("e6e95769-d406-4fd0-ae98-a21ca99c8d38")]
            public virtual RepoItemInfo FieldFormaInfo
            {
                get
                {
                    return _fieldformaInfo;
                }
            }

            /// <summary>
            /// The FieldCadruDidactic item.
            /// </summary>
            [RepositoryItem("a926d200-3240-4965-8e8c-7723e5e22958")]
            public virtual Ranorex.SelectTag FieldCadruDidactic
            {
                get
                {
                    return _fieldcadrudidacticInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The FieldCadruDidactic item info.
            /// </summary>
            [RepositoryItemInfo("a926d200-3240-4965-8e8c-7723e5e22958")]
            public virtual RepoItemInfo FieldCadruDidacticInfo
            {
                get
                {
                    return _fieldcadrudidacticInfo;
                }
            }

            /// <summary>
            /// The JhiConfirmDeleteStudent item.
            /// </summary>
            [RepositoryItem("ec6d5931-482f-4e69-9fb2-bcb0493c2b46")]
            public virtual Ranorex.ButtonTag JhiConfirmDeleteStudent
            {
                get
                {
                    return _jhiconfirmdeletestudentInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The JhiConfirmDeleteStudent item info.
            /// </summary>
            [RepositoryItemInfo("ec6d5931-482f-4e69-9fb2-bcb0493c2b46")]
            public virtual RepoItemInfo JhiConfirmDeleteStudentInfo
            {
                get
                {
                    return _jhiconfirmdeletestudentInfo;
                }
            }

            /// <summary>
            /// The Ștergere item.
            /// </summary>
            [RepositoryItem("39379724-86b8-4e47-abde-5e66a74317cc")]
            public virtual Ranorex.SpanTag Ștergere
            {
                get
                {
                    return _ștergereInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Ștergere item info.
            /// </summary>
            [RepositoryItemInfo("39379724-86b8-4e47-abde-5e66a74317cc")]
            public virtual RepoItemInfo ȘtergereInfo
            {
                get
                {
                    return _ștergereInfo;
                }
            }

            /// <summary>
            /// The JhiConfirmDeleteCadruDidactic item.
            /// </summary>
            [RepositoryItem("159cc891-ca22-4988-bea6-d0b9f51e37f2")]
            public virtual Ranorex.ButtonTag JhiConfirmDeleteCadruDidactic
            {
                get
                {
                    return _jhiconfirmdeletecadrudidacticInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The JhiConfirmDeleteCadruDidactic item info.
            /// </summary>
            [RepositoryItemInfo("159cc891-ca22-4988-bea6-d0b9f51e37f2")]
            public virtual RepoItemInfo JhiConfirmDeleteCadruDidacticInfo
            {
                get
                {
                    return _jhiconfirmdeletecadrudidacticInfo;
                }
            }

            /// <summary>
            /// The JhiConfirmDeleteProgramStudiu item.
            /// </summary>
            [RepositoryItem("fba45fcd-e0ab-4391-ab06-863dbda8325f")]
            public virtual Ranorex.ButtonTag JhiConfirmDeleteProgramStudiu
            {
                get
                {
                    return _jhiconfirmdeleteprogramstudiuInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The JhiConfirmDeleteProgramStudiu item info.
            /// </summary>
            [RepositoryItemInfo("fba45fcd-e0ab-4391-ab06-863dbda8325f")]
            public virtual RepoItemInfo JhiConfirmDeleteProgramStudiuInfo
            {
                get
                {
                    return _jhiconfirmdeleteprogramstudiuInfo;
                }
            }

            /// <summary>
            /// The JhiConfirmDeleteDepartament item.
            /// </summary>
            [RepositoryItem("1d998b2f-319c-48b6-9c9c-f523f33be1e3")]
            public virtual Ranorex.ButtonTag JhiConfirmDeleteDepartament
            {
                get
                {
                    return _jhiconfirmdeletedepartamentInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The JhiConfirmDeleteDepartament item info.
            /// </summary>
            [RepositoryItemInfo("1d998b2f-319c-48b6-9c9c-f523f33be1e3")]
            public virtual RepoItemInfo JhiConfirmDeleteDepartamentInfo
            {
                get
                {
                    return _jhiconfirmdeletedepartamentInfo;
                }
            }

            /// <summary>
            /// The BtnBtnDanger item.
            /// </summary>
            [RepositoryItem("5711b431-9146-4249-8780-183b80f3b236")]
            public virtual Ranorex.ButtonTag BtnBtnDanger
            {
                get
                {
                    return _btnbtndangerInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The BtnBtnDanger item info.
            /// </summary>
            [RepositoryItemInfo("5711b431-9146-4249-8780-183b80f3b236")]
            public virtual RepoItemInfo BtnBtnDangerInfo
            {
                get
                {
                    return _btnbtndangerInfo;
                }
            }

            /// <summary>
            /// The Password1 item.
            /// </summary>
            [RepositoryItem("6d6bcfed-2ad7-4383-882c-5cf5c19a7541")]
            public virtual Ranorex.InputTag Password1
            {
                get
                {
                    return _password1Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Password1 item info.
            /// </summary>
            [RepositoryItemInfo("6d6bcfed-2ad7-4383-882c-5cf5c19a7541")]
            public virtual RepoItemInfo Password1Info
            {
                get
                {
                    return _password1Info;
                }
            }

            /// <summary>
            /// The CardJhCard folder.
            /// </summary>
            [RepositoryFolder("240ee1ba-fb33-4d43-9d7c-0821846f10c7")]
            public virtual Licenta_NohaiRepositoryFolders.CardJhCardFolder CardJhCard
            {
                get { return _cardjhcard; }
            }

            /// <summary>
            /// The ContainerFluid folder.
            /// </summary>
            [RepositoryFolder("10aba48c-300c-459f-8229-6bc498a2e6f3")]
            public virtual Licenta_NohaiRepositoryFolders.ContainerFluidFolder ContainerFluid
            {
                get { return _containerfluid; }
            }
        }

        /// <summary>
        /// The CardJhCardFolder folder.
        /// </summary>
        [RepositoryFolder("240ee1ba-fb33-4d43-9d7c-0821846f10c7")]
        public partial class CardJhCardFolder : RepoGenBaseFolder
        {
            RepoItemInfo _inregistrareInfo;
            RepoItemInfo _login1Info;
            RepoItemInfo _inregistrațiuncontnouInfo;
            RepoItemInfo _divtagvărugămsăvăverificațiemailulInfo;
            RepoItemInfo _autentificațiInfo;
            RepoItemInfo _salvareInfo;
            RepoItemInfo _autentificați1Info;
            RepoItemInfo _salvare1Info;
            RepoItemInfo _alertalertsuccessInfo;
            RepoItemInfo _ngbalertInfo;

            /// <summary>
            /// Creates a new CardJhCard  folder.
            /// </summary>
            public CardJhCardFolder(RepoGenBaseFolder parentFolder) :
                    base("CardJhCard", "body/tag[@tagname='jhi-main']/div[2]/div", parentFolder, 30000, null, false, "240ee1ba-fb33-4d43-9d7c-0821846f10c7", "")
            {
                _inregistrareInfo = new RepoItemInfo(this, "Inregistrare", ".//form[@name='form']/button[@innertext='Înregistrare']", 30000, null, "1025c1d1-7526-427a-82e5-b51109503697");
                _login1Info = new RepoItemInfo(this, "Login1", ".//form[@name='form']/div[1]/input[@id='login']", 30000, null, "99e88655-f35e-40f0-bce2-3fe8ff4f3da5");
                _inregistrațiuncontnouInfo = new RepoItemInfo(this, "InregistrațiUnContNou", "tag[@tagname='jhi-home']/div/div[2]/div/?/?/a[@innertext='Înregistrați un cont nou']", 30000, null, "5195b462-851d-4a79-ab59-46ae0ff51737");
                _divtagvărugămsăvăverificațiemailulInfo = new RepoItemInfo(this, "DivTagVăRugămSăVăVerificațiEmailul", "tag[@tagname='jhi-register']/div/div[1]/?/?/div[@innertext>' Vă rugăm să vă verificați']", 30000, null, "f344f00e-9396-4ed3-b866-09daedc1a1bd");
                _autentificațiInfo = new RepoItemInfo(this, "Autentificați", "tag[@tagname='jhi-register']/div/div[2]//a[@innertext='autentificați']", 30000, null, "bd8fa4aa-0ef3-49dc-8f05-f83b3af23619");
                _salvareInfo = new RepoItemInfo(this, "Salvare", ".//form[@name='editForm']/div[2]/?/?/span[@innertext='Salvare']", 30000, null, "9962ac3a-1c98-4bd1-87f2-aa6fd2664604");
                _autentificați1Info = new RepoItemInfo(this, "Autentificați1", "tag[@tagname='jhi-home']/div/div[2]/div/?/?/a[@innertext='autentificați']", 30000, null, "92fd7f82-e808-46a0-9912-ad562a0a0249");
                _salvare1Info = new RepoItemInfo(this, "Salvare1", ".//form[@name='form']/button[@innertext='Salvare']", 30000, null, "1dea1d15-2c32-4a6a-8c00-16b8b3f56881");
                _alertalertsuccessInfo = new RepoItemInfo(this, "AlertAlertSuccess", "tag[@tagname='jhi-settings']/div/div/div/div", 30000, null, "a3824cc2-7c8b-4c52-ba64-bfe9a9bb96c5");
                _ngbalertInfo = new RepoItemInfo(this, "NgbAlert", "tag[@tagname='jhi-user-mgmt']/div//tag[@tagname='ngb-alert']", 30000, null, "39c5d3d6-ecf9-489b-9eb7-01b87b3e083e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("240ee1ba-fb33-4d43-9d7c-0821846f10c7")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("240ee1ba-fb33-4d43-9d7c-0821846f10c7")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Inregistrare item.
            /// </summary>
            [RepositoryItem("1025c1d1-7526-427a-82e5-b51109503697")]
            public virtual Ranorex.ButtonTag Inregistrare
            {
                get
                {
                    return _inregistrareInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The Inregistrare item info.
            /// </summary>
            [RepositoryItemInfo("1025c1d1-7526-427a-82e5-b51109503697")]
            public virtual RepoItemInfo InregistrareInfo
            {
                get
                {
                    return _inregistrareInfo;
                }
            }

            /// <summary>
            /// The Login1 item.
            /// </summary>
            [RepositoryItem("99e88655-f35e-40f0-bce2-3fe8ff4f3da5")]
            public virtual Ranorex.InputTag Login1
            {
                get
                {
                    return _login1Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Login1 item info.
            /// </summary>
            [RepositoryItemInfo("99e88655-f35e-40f0-bce2-3fe8ff4f3da5")]
            public virtual RepoItemInfo Login1Info
            {
                get
                {
                    return _login1Info;
                }
            }

            /// <summary>
            /// The InregistrațiUnContNou item.
            /// </summary>
            [RepositoryItem("5195b462-851d-4a79-ab59-46ae0ff51737")]
            public virtual Ranorex.ATag InregistrațiUnContNou
            {
                get
                {
                    return _inregistrațiuncontnouInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The InregistrațiUnContNou item info.
            /// </summary>
            [RepositoryItemInfo("5195b462-851d-4a79-ab59-46ae0ff51737")]
            public virtual RepoItemInfo InregistrațiUnContNouInfo
            {
                get
                {
                    return _inregistrațiuncontnouInfo;
                }
            }

            /// <summary>
            /// The DivTagVăRugămSăVăVerificațiEmailul item.
            /// </summary>
            [RepositoryItem("f344f00e-9396-4ed3-b866-09daedc1a1bd")]
            public virtual Ranorex.DivTag DivTagVăRugămSăVăVerificațiEmailul
            {
                get
                {
                    return _divtagvărugămsăvăverificațiemailulInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The DivTagVăRugămSăVăVerificațiEmailul item info.
            /// </summary>
            [RepositoryItemInfo("f344f00e-9396-4ed3-b866-09daedc1a1bd")]
            public virtual RepoItemInfo DivTagVăRugămSăVăVerificațiEmailulInfo
            {
                get
                {
                    return _divtagvărugămsăvăverificațiemailulInfo;
                }
            }

            /// <summary>
            /// The Autentificați item.
            /// </summary>
            [RepositoryItem("bd8fa4aa-0ef3-49dc-8f05-f83b3af23619")]
            public virtual Ranorex.ATag Autentificați
            {
                get
                {
                    return _autentificațiInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Autentificați item info.
            /// </summary>
            [RepositoryItemInfo("bd8fa4aa-0ef3-49dc-8f05-f83b3af23619")]
            public virtual RepoItemInfo AutentificațiInfo
            {
                get
                {
                    return _autentificațiInfo;
                }
            }

            /// <summary>
            /// The Salvare item.
            /// </summary>
            [RepositoryItem("9962ac3a-1c98-4bd1-87f2-aa6fd2664604")]
            public virtual Ranorex.SpanTag Salvare
            {
                get
                {
                    return _salvareInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Salvare item info.
            /// </summary>
            [RepositoryItemInfo("9962ac3a-1c98-4bd1-87f2-aa6fd2664604")]
            public virtual RepoItemInfo SalvareInfo
            {
                get
                {
                    return _salvareInfo;
                }
            }

            /// <summary>
            /// The Autentificați1 item.
            /// </summary>
            [RepositoryItem("92fd7f82-e808-46a0-9912-ad562a0a0249")]
            public virtual Ranorex.ATag Autentificați1
            {
                get
                {
                    return _autentificați1Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Autentificați1 item info.
            /// </summary>
            [RepositoryItemInfo("92fd7f82-e808-46a0-9912-ad562a0a0249")]
            public virtual RepoItemInfo Autentificați1Info
            {
                get
                {
                    return _autentificați1Info;
                }
            }

            /// <summary>
            /// The Salvare1 item.
            /// </summary>
            [RepositoryItem("1dea1d15-2c32-4a6a-8c00-16b8b3f56881")]
            public virtual Ranorex.ButtonTag Salvare1
            {
                get
                {
                    return _salvare1Info.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The Salvare1 item info.
            /// </summary>
            [RepositoryItemInfo("1dea1d15-2c32-4a6a-8c00-16b8b3f56881")]
            public virtual RepoItemInfo Salvare1Info
            {
                get
                {
                    return _salvare1Info;
                }
            }

            /// <summary>
            /// The AlertAlertSuccess item.
            /// </summary>
            [RepositoryItem("a3824cc2-7c8b-4c52-ba64-bfe9a9bb96c5")]
            public virtual Ranorex.DivTag AlertAlertSuccess
            {
                get
                {
                    return _alertalertsuccessInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The AlertAlertSuccess item info.
            /// </summary>
            [RepositoryItemInfo("a3824cc2-7c8b-4c52-ba64-bfe9a9bb96c5")]
            public virtual RepoItemInfo AlertAlertSuccessInfo
            {
                get
                {
                    return _alertalertsuccessInfo;
                }
            }

            /// <summary>
            /// The NgbAlert item.
            /// </summary>
            [RepositoryItem("39c5d3d6-ecf9-489b-9eb7-01b87b3e083e")]
            public virtual Ranorex.WebElement NgbAlert
            {
                get
                {
                    return _ngbalertInfo.CreateAdapter<Ranorex.WebElement>(true);
                }
            }

            /// <summary>
            /// The NgbAlert item info.
            /// </summary>
            [RepositoryItemInfo("39c5d3d6-ecf9-489b-9eb7-01b87b3e083e")]
            public virtual RepoItemInfo NgbAlertInfo
            {
                get
                {
                    return _ngbalertInfo;
                }
            }
        }

        /// <summary>
        /// The ContainerFluidFolder folder.
        /// </summary>
        [RepositoryFolder("10aba48c-300c-459f-8229-6bc498a2e6f3")]
        public partial class ContainerFluidFolder : RepoGenBaseFolder
        {
            RepoItemInfo _optiontag0roleadminInfo;
            RepoItemInfo _editareInfo;
            RepoItemInfo _dezactivatInfo;
            RepoItemInfo _btnbtndangerbtnsmInfo;
            RepoItemInfo _faiconInfo;
            RepoItemInfo _btnbtndangerbtnsm1Info;
            RepoItemInfo _btnbtndangerbtnsm2Info;
            RepoItemInfo _btnbtndangerbtnsm3Info;
            RepoItemInfo _btnbtndangerbtnsm4Info;
            RepoItemInfo _optiontag1roleuserInfo;
            RepoItemInfo _btnbtnprimarybtnsmInfo;

            /// <summary>
            /// Creates a new ContainerFluid  folder.
            /// </summary>
            public ContainerFluidFolder(RepoGenBaseFolder parentFolder) :
                    base("ContainerFluid", "?/?/tag[@tagname='jhi-main']/div[2]", parentFolder, 30000, null, false, "10aba48c-300c-459f-8229-6bc498a2e6f3", "")
            {
                _optiontag0roleadminInfo = new RepoItemInfo(this, "OptionTag0ROLEADMIN", ".//form[@name='editForm']/div[1]/div[8]/select[@name='authority']/option[@value='0: ''ROLE_ADMIN''']", 30000, null, "68f52211-6e55-4258-8691-8e0272b7eecc");
                _editareInfo = new RepoItemInfo(this, "Editare", "?/?/tag[@tagname='jhi-user-mgmt']/div/div[1]/table/tbody/tr[4]/td[10]/div/button[2]/span[@innertext='Editare']", 30000, null, "bb4134fd-e3f4-4642-87c9-44755c075057");
                _dezactivatInfo = new RepoItemInfo(this, "Dezactivat", "?/?/tag[@tagname='jhi-user-mgmt']/div/div[1]/table/tbody/tr[4]/td[4]/button[@innertext='Dezactivat']", 30000, null, "dea7be6e-a634-4302-af94-af0d117aca97");
                _btnbtndangerbtnsmInfo = new RepoItemInfo(this, "BtnBtnDangerBtnSm", "?/?/tag[@tagname='jhi-student']/div/div[1]/table/tbody/tr[1]/td[9]/div/button[3]", 30000, null, "d714a52f-3420-42a5-bce5-098810e1c5b1");
                _faiconInfo = new RepoItemInfo(this, "FaIcon", "?/?/tag[@tagname='jhi-student']/div/div[1]/table/tbody/tr[1]/td[9]/div/button[3]/tag[@tagname='fa-icon']", 30000, null, "b027f457-2541-4334-afba-8a89bd852fbc");
                _btnbtndangerbtnsm1Info = new RepoItemInfo(this, "BtnBtnDangerBtnSm1", "?/?/tag[@tagname='jhi-cadru-didactic']/div/div[1]/table/tbody/tr[1]/td[8]/div/button[3]", 30000, null, "f71f63c7-b3a8-4227-8071-d33eee61fdde");
                _btnbtndangerbtnsm2Info = new RepoItemInfo(this, "BtnBtnDangerBtnSm2", "?/?/tag[@tagname='jhi-program-studiu']/div/div/table/tbody/tr[1]/td[4]/div/button[3]", 30000, null, "cf34c42a-2983-4d4b-85e9-64a47faa535b");
                _btnbtndangerbtnsm3Info = new RepoItemInfo(this, "BtnBtnDangerBtnSm3", "?/?/tag[@tagname='jhi-departament']/div/div[1]/table/tbody/tr[1]/td[3]/div/button[3]", 30000, null, "fb5c2bcf-df47-440f-97ec-e110a3587575");
                _btnbtndangerbtnsm4Info = new RepoItemInfo(this, "BtnBtnDangerBtnSm4", "?/?/tag[@tagname='jhi-user-mgmt']/div/div[1]/table/tbody/tr[4]/td[10]/div/button[3]", 30000, null, "4c0f76d2-1677-4056-ab3c-e23faef7249d");
                _optiontag1roleuserInfo = new RepoItemInfo(this, "OptionTag1ROLEUSER", ".//form[@name='editForm']/div[1]/div[8]/select[@name='authority']/option[@value='1: ''ROLE_USER''']", 30000, null, "610e81b9-5912-49fe-b686-078cb4230614");
                _btnbtnprimarybtnsmInfo = new RepoItemInfo(this, "BtnBtnPrimaryBtnSm", "?/?/tag[@tagname='jhi-user-mgmt']/div/div[1]/table/tbody/tr[4]/td[10]/div/button[2]", 30000, null, "1d83e3f1-f2d1-4d80-82a5-057597983c1b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("10aba48c-300c-459f-8229-6bc498a2e6f3")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("10aba48c-300c-459f-8229-6bc498a2e6f3")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The OptionTag0ROLEADMIN item.
            /// </summary>
            [RepositoryItem("68f52211-6e55-4258-8691-8e0272b7eecc")]
            public virtual Ranorex.OptionTag OptionTag0ROLEADMIN
            {
                get
                {
                    return _optiontag0roleadminInfo.CreateAdapter<Ranorex.OptionTag>(true);
                }
            }

            /// <summary>
            /// The OptionTag0ROLEADMIN item info.
            /// </summary>
            [RepositoryItemInfo("68f52211-6e55-4258-8691-8e0272b7eecc")]
            public virtual RepoItemInfo OptionTag0ROLEADMINInfo
            {
                get
                {
                    return _optiontag0roleadminInfo;
                }
            }

            /// <summary>
            /// The Editare item.
            /// </summary>
            [RepositoryItem("bb4134fd-e3f4-4642-87c9-44755c075057")]
            public virtual Ranorex.SpanTag Editare
            {
                get
                {
                    return _editareInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Editare item info.
            /// </summary>
            [RepositoryItemInfo("bb4134fd-e3f4-4642-87c9-44755c075057")]
            public virtual RepoItemInfo EditareInfo
            {
                get
                {
                    return _editareInfo;
                }
            }

            /// <summary>
            /// The Dezactivat item.
            /// </summary>
            [RepositoryItem("dea7be6e-a634-4302-af94-af0d117aca97")]
            public virtual Ranorex.ButtonTag Dezactivat
            {
                get
                {
                    return _dezactivatInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The Dezactivat item info.
            /// </summary>
            [RepositoryItemInfo("dea7be6e-a634-4302-af94-af0d117aca97")]
            public virtual RepoItemInfo DezactivatInfo
            {
                get
                {
                    return _dezactivatInfo;
                }
            }

            /// <summary>
            /// The BtnBtnDangerBtnSm item.
            /// </summary>
            [RepositoryItem("d714a52f-3420-42a5-bce5-098810e1c5b1")]
            public virtual Ranorex.ButtonTag BtnBtnDangerBtnSm
            {
                get
                {
                    return _btnbtndangerbtnsmInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The BtnBtnDangerBtnSm item info.
            /// </summary>
            [RepositoryItemInfo("d714a52f-3420-42a5-bce5-098810e1c5b1")]
            public virtual RepoItemInfo BtnBtnDangerBtnSmInfo
            {
                get
                {
                    return _btnbtndangerbtnsmInfo;
                }
            }

            /// <summary>
            /// The FaIcon item.
            /// </summary>
            [RepositoryItem("b027f457-2541-4334-afba-8a89bd852fbc")]
            public virtual Ranorex.WebElement FaIcon
            {
                get
                {
                    return _faiconInfo.CreateAdapter<Ranorex.WebElement>(true);
                }
            }

            /// <summary>
            /// The FaIcon item info.
            /// </summary>
            [RepositoryItemInfo("b027f457-2541-4334-afba-8a89bd852fbc")]
            public virtual RepoItemInfo FaIconInfo
            {
                get
                {
                    return _faiconInfo;
                }
            }

            /// <summary>
            /// The BtnBtnDangerBtnSm1 item.
            /// </summary>
            [RepositoryItem("f71f63c7-b3a8-4227-8071-d33eee61fdde")]
            public virtual Ranorex.ButtonTag BtnBtnDangerBtnSm1
            {
                get
                {
                    return _btnbtndangerbtnsm1Info.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The BtnBtnDangerBtnSm1 item info.
            /// </summary>
            [RepositoryItemInfo("f71f63c7-b3a8-4227-8071-d33eee61fdde")]
            public virtual RepoItemInfo BtnBtnDangerBtnSm1Info
            {
                get
                {
                    return _btnbtndangerbtnsm1Info;
                }
            }

            /// <summary>
            /// The BtnBtnDangerBtnSm2 item.
            /// </summary>
            [RepositoryItem("cf34c42a-2983-4d4b-85e9-64a47faa535b")]
            public virtual Ranorex.ButtonTag BtnBtnDangerBtnSm2
            {
                get
                {
                    return _btnbtndangerbtnsm2Info.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The BtnBtnDangerBtnSm2 item info.
            /// </summary>
            [RepositoryItemInfo("cf34c42a-2983-4d4b-85e9-64a47faa535b")]
            public virtual RepoItemInfo BtnBtnDangerBtnSm2Info
            {
                get
                {
                    return _btnbtndangerbtnsm2Info;
                }
            }

            /// <summary>
            /// The BtnBtnDangerBtnSm3 item.
            /// </summary>
            [RepositoryItem("fb5c2bcf-df47-440f-97ec-e110a3587575")]
            public virtual Ranorex.ButtonTag BtnBtnDangerBtnSm3
            {
                get
                {
                    return _btnbtndangerbtnsm3Info.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The BtnBtnDangerBtnSm3 item info.
            /// </summary>
            [RepositoryItemInfo("fb5c2bcf-df47-440f-97ec-e110a3587575")]
            public virtual RepoItemInfo BtnBtnDangerBtnSm3Info
            {
                get
                {
                    return _btnbtndangerbtnsm3Info;
                }
            }

            /// <summary>
            /// The BtnBtnDangerBtnSm4 item.
            /// </summary>
            [RepositoryItem("4c0f76d2-1677-4056-ab3c-e23faef7249d")]
            public virtual Ranorex.ButtonTag BtnBtnDangerBtnSm4
            {
                get
                {
                    return _btnbtndangerbtnsm4Info.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The BtnBtnDangerBtnSm4 item info.
            /// </summary>
            [RepositoryItemInfo("4c0f76d2-1677-4056-ab3c-e23faef7249d")]
            public virtual RepoItemInfo BtnBtnDangerBtnSm4Info
            {
                get
                {
                    return _btnbtndangerbtnsm4Info;
                }
            }

            /// <summary>
            /// The OptionTag1ROLEUSER item.
            /// </summary>
            [RepositoryItem("610e81b9-5912-49fe-b686-078cb4230614")]
            public virtual Ranorex.OptionTag OptionTag1ROLEUSER
            {
                get
                {
                    return _optiontag1roleuserInfo.CreateAdapter<Ranorex.OptionTag>(true);
                }
            }

            /// <summary>
            /// The OptionTag1ROLEUSER item info.
            /// </summary>
            [RepositoryItemInfo("610e81b9-5912-49fe-b686-078cb4230614")]
            public virtual RepoItemInfo OptionTag1ROLEUSERInfo
            {
                get
                {
                    return _optiontag1roleuserInfo;
                }
            }

            /// <summary>
            /// The BtnBtnPrimaryBtnSm item.
            /// </summary>
            [RepositoryItem("1d83e3f1-f2d1-4d80-82a5-057597983c1b")]
            public virtual Ranorex.ButtonTag BtnBtnPrimaryBtnSm
            {
                get
                {
                    return _btnbtnprimarybtnsmInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The BtnBtnPrimaryBtnSm item info.
            /// </summary>
            [RepositoryItemInfo("1d83e3f1-f2d1-4d80-82a5-057597983c1b")]
            public virtual RepoItemInfo BtnBtnPrimaryBtnSmInfo
            {
                get
                {
                    return _btnbtnprimarybtnsmInfo;
                }
            }
        }

        /// <summary>
        /// The DropdownAppFolder folder.
        /// </summary>
        [RepositoryFolder("718c5e3b-9139-43f7-88f0-3a761798ba93")]
        public partial class DropdownAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new Dropdown  folder.
            /// </summary>
            public DropdownAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Dropdown", "/container[@caption='dropdown']", parentFolder, 30000, null, true, "718c5e3b-9139-43f7-88f0-3a761798ba93", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("718c5e3b-9139-43f7-88f0-3a761798ba93")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("718c5e3b-9139-43f7-88f0-3a761798ba93")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
