///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Licenta_Nohai
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Login_as_admin recording.
    /// </summary>
    [TestModule("349a35a9-7673-468d-9f42-57c46b514280", ModuleType.Recording, 1)]
    public partial class Login_as_admin : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Licenta_NohaiRepository repository.
        /// </summary>
        public static Licenta_NohaiRepository repo = Licenta_NohaiRepository.Instance;

        static Login_as_admin instance = new Login_as_admin();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Login_as_admin()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Login_as_admin Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.AccountMenu' at Center.", repo.ApplicationUnderTest.AccountMenuInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.AccountMenu.Click();
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Login' at Center.", repo.ApplicationUnderTest.LoginInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.Login.Click();
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Username' at Center.", repo.ApplicationUnderTest.UsernameInfo, new RecordItemIndex(2));
            //repo.ApplicationUnderTest.Username.Click();
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'admin' with focus on 'ApplicationUnderTest.Username'.", repo.ApplicationUnderTest.UsernameInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.Username.PressKeys("admin");
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Password' at Center.", repo.ApplicationUnderTest.PasswordInfo, new RecordItemIndex(4));
            //repo.ApplicationUnderTest.Password.Click();
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'admin' with focus on 'ApplicationUnderTest.Password'.", repo.ApplicationUnderTest.PasswordInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.Password.PressKeys("admin");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.RememberMe' at Center.", repo.ApplicationUnderTest.RememberMeInfo, new RecordItemIndex(6));
            repo.ApplicationUnderTest.RememberMe.Click();
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Autentificare' at Center.", repo.ApplicationUnderTest.AutentificareInfo, new RecordItemIndex(7));
            repo.ApplicationUnderTest.Autentificare.Click();
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
