///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Licenta_Nohai
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Register_new_user recording.
    /// </summary>
    [TestModule("6b078cab-feeb-424f-8238-01d6fb328dce", ModuleType.Recording, 1)]
    public partial class Register_new_user : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Licenta_NohaiRepository repository.
        /// </summary>
        public static Licenta_NohaiRepository repo = Licenta_NohaiRepository.Instance;

        static Register_new_user instance = new Register_new_user();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Register_new_user()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Register_new_user Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.CardJhCard.InregistrațiUnContNou' at Center.", repo.ApplicationUnderTest.CardJhCard.InregistrațiUnContNouInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.CardJhCard.InregistrațiUnContNou.Click();
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.CardJhCard.Login1' at Center.", repo.ApplicationUnderTest.CardJhCard.Login1Info, new RecordItemIndex(1));
            //repo.ApplicationUnderTest.CardJhCard.Login1.Click();
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'DragosIonut' with focus on 'ApplicationUnderTest.CardJhCard.Login1'.", repo.ApplicationUnderTest.CardJhCard.Login1Info, new RecordItemIndex(2));
            repo.ApplicationUnderTest.CardJhCard.Login1.PressKeys("DragosIonut");
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Email' at Center.", repo.ApplicationUnderTest.EmailInfo, new RecordItemIndex(3));
            //repo.ApplicationUnderTest.Email.Click();
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'dragosionut115@gmail.com' with focus on 'ApplicationUnderTest.Email'.", repo.ApplicationUnderTest.EmailInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.Email.PressKeys("dragosionut115@gmail.com");
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Password1' at Center.", repo.ApplicationUnderTest.Password1Info, new RecordItemIndex(5));
            //repo.ApplicationUnderTest.Password1.Click();
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'nohaidragos' with focus on 'ApplicationUnderTest.Password1'.", repo.ApplicationUnderTest.Password1Info, new RecordItemIndex(6));
            repo.ApplicationUnderTest.Password1.PressKeys("nohaidragos");
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.ConfirmPassword' at Center.", repo.ApplicationUnderTest.ConfirmPasswordInfo, new RecordItemIndex(7));
            //repo.ApplicationUnderTest.ConfirmPassword.Click();
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'nohaidragos' with focus on 'ApplicationUnderTest.ConfirmPassword'.", repo.ApplicationUnderTest.ConfirmPasswordInfo, new RecordItemIndex(8));
            repo.ApplicationUnderTest.ConfirmPassword.PressKeys("nohaidragos");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.CardJhCard.Inregistrare' at Center.", repo.ApplicationUnderTest.CardJhCard.InregistrareInfo, new RecordItemIndex(9));
            repo.ApplicationUnderTest.CardJhCard.Inregistrare.Click();
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ApplicationUnderTest.CardJhCard.DivTagVăRugămSăVăVerificațiEmailul'.", repo.ApplicationUnderTest.CardJhCard.DivTagVăRugămSăVăVerificațiEmailulInfo, new RecordItemIndex(10));
            Validate.Exists(repo.ApplicationUnderTest.CardJhCard.DivTagVăRugămSăVăVerificațiEmailulInfo);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
